-- Theme writer - saves and applies themes

local M = {}

-- Default themes directory
M.themes_dir = vim.fn.stdpath('config') .. '/themes'

-- Counter for auto-generated theme names
local theme_counter = 1

-- Ensure themes directory exists
function M.ensure_themes_dir()
  if vim.fn.isdirectory(M.themes_dir) == 0 then
    vim.fn.mkdir(M.themes_dir, 'p')
  end
end

-- Generate auto theme name
-- @param theme_type string: "dark" or "light"
-- @param preset string: preset name
-- @return string: theme name like "mltb-dark-soft-001"
function M.generate_theme_name(theme_type, preset)
  -- Sanitize preset name (remove spaces)
  local sanitized_preset = preset:gsub("%s+", "-")

  -- Find next available number
  local name
  repeat
    name = string.format("mltb-%s-%s-%03d", theme_type, sanitized_preset, theme_counter)
    theme_counter = theme_counter + 1
  until vim.fn.filereadable(M.themes_dir .. '/' .. name .. '.lua') == 0

  return name
end

-- Apply a theme immediately (live preview)
-- @param theme table: theme object
function M.apply_theme(theme)
  -- Clear existing highlights
  vim.cmd('highlight clear')

  -- Set background
  vim.o.background = theme.type

  -- Apply all highlights
  for group_name, group_attrs in pairs(theme.highlights) do
    vim.api.nvim_set_hl(0, group_name, group_attrs)
  end
end

-- Convert highlight attributes to Lua code string
-- @param attrs table: highlight attributes
-- @return string: Lua code
local function attrs_to_string(attrs)
  local parts = {}

  for key, value in pairs(attrs) do
    if type(value) == "string" then
      table.insert(parts, string.format('%s = "%s"', key, value))
    elseif type(value) == "boolean" then
      table.insert(parts, string.format('%s = %s', key, tostring(value)))
    elseif type(value) == "number" then
      table.insert(parts, string.format('%s = %d', key, value))
    end
  end

  return "{" .. table.concat(parts, ", ") .. "}"
end

-- Save theme to file
-- @param theme table: theme object
-- @param theme_name string: theme name
-- @return string: full path to saved file
function M.save_theme(theme, theme_name)
  M.ensure_themes_dir()

  local filepath = M.themes_dir .. '/' .. theme_name .. '.lua'

  -- Build file content
  local lines = {}

  -- Header
  table.insert(lines, "-- Theme: " .. theme_name)
  table.insert(lines, "-- Type: " .. theme.type)
  table.insert(lines, "-- Generated by MLTB (My Lovely Theme Builder)")
  table.insert(lines, "")

  -- Clear and setup
  table.insert(lines, "vim.cmd('highlight clear')")
  table.insert(lines, "vim.o.background = '" .. theme.type .. "'")
  table.insert(lines, "vim.g.colors_name = '" .. theme_name .. "'")
  table.insert(lines, "")

  -- Highlight groups
  table.insert(lines, "-- Highlights")
  for group_name, group_attrs in pairs(theme.highlights) do
    local attrs_str = attrs_to_string(group_attrs)
    table.insert(lines, string.format("vim.api.nvim_set_hl(0, '%s', %s)", group_name, attrs_str))
  end

  -- Terminal colors
  table.insert(lines, "")
  table.insert(lines, "-- Terminal colors")
  local p = theme.palette
  table.insert(lines, string.format("vim.g.terminal_color_0 = '%s'", p.bg))
  table.insert(lines, string.format("vim.g.terminal_color_1 = '%s'", p.red))
  table.insert(lines, string.format("vim.g.terminal_color_2 = '%s'", p.green))
  table.insert(lines, string.format("vim.g.terminal_color_3 = '%s'", p.yellow))
  table.insert(lines, string.format("vim.g.terminal_color_4 = '%s'", p.blue))
  table.insert(lines, string.format("vim.g.terminal_color_5 = '%s'", p.purple))
  table.insert(lines, string.format("vim.g.terminal_color_6 = '%s'", p.cyan))
  table.insert(lines, string.format("vim.g.terminal_color_7 = '%s'", p.fg))
  table.insert(lines, string.format("vim.g.terminal_color_8 = '%s'", p.bg))
  table.insert(lines, string.format("vim.g.terminal_color_9 = '%s'", p.red))
  table.insert(lines, string.format("vim.g.terminal_color_10 = '%s'", p.green))
  table.insert(lines, string.format("vim.g.terminal_color_11 = '%s'", p.yellow))
  table.insert(lines, string.format("vim.g.terminal_color_12 = '%s'", p.blue))
  table.insert(lines, string.format("vim.g.terminal_color_13 = '%s'", p.purple))
  table.insert(lines, string.format("vim.g.terminal_color_14 = '%s'", p.cyan))
  table.insert(lines, string.format("vim.g.terminal_color_15 = '%s'", p.fg))

  -- Write to file
  local file = io.open(filepath, 'w')
  if file then
    file:write(table.concat(lines, '\n'))
    file:close()
    return filepath
  else
    error("Failed to write theme file: " .. filepath)
  end
end

-- Delete theme file
-- @param theme_name string: theme name (without .lua extension)
function M.delete_theme(theme_name)
  local filepath = M.themes_dir .. '/' .. theme_name .. '.lua'
  if vim.fn.filereadable(filepath) == 1 then
    vim.fn.delete(filepath)
  end
end

-- List all themes in themes directory
-- @return table: list of theme names (without .lua extension)
function M.list_themes()
  M.ensure_themes_dir()

  local themes = {}
  local files = vim.fn.glob(M.themes_dir .. '/*.lua', false, true)

  for _, filepath in ipairs(files) do
    local filename = vim.fn.fnamemodify(filepath, ':t:r')
    table.insert(themes, filename)
  end

  table.sort(themes)
  return themes
end

return M
